default_stages: [commit, push]
default_language_version:
  python: python3.10
exclude: migrations
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=backend/setup.cfg]
        additional_dependencies: [flake8-docstrings==1.6.0, flake8-print==4.0.0]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--config-file=backend/setup.cfg]
        additional_dependencies:
          [
            fastapi==0.75.1,
            jinja2==3.1.1,
            sqlmodel==0.0.6,
            types-freezegun==1.1.8,
            types-orjson==3.6.2,
            types-redis==4.1.19,
          ]
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.4
    hooks:
      - id: pylint
        args: [--rcfile=backend/setup.cfg]
        additional_dependencies:
          [fastapi==0.75.1, orjson==3.6.7, pydantic==1.9.0]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--exclude, tests, --recursive, .]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: ["--fix --ext .js,.jsx,.ts,.tsx"]
