default_stages: [commit, push]
default_language_version:
  python: python3.10
exclude: migrations
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=backend/setup.cfg]
        additional_dependencies: [flake8-docstrings==1.6.0, flake8-print==5.0.0]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--config-file=backend/setup.cfg]
        additional_dependencies:
          [
            fastapi==0.78.0,
            jinja2==3.1.2,
            sentry-sdk==1.6.0,
            sqlmodel==0.0.6,
            types-freezegun==1.1.10,
            types-orjson==3.6.2,
            types-redis==4.3.2,
          ]
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.3
    hooks:
      - id: pylint
        args: [--rcfile=backend/setup.cfg]
        additional_dependencies:
          [
            fastapi==0.78.0,
            orjson==3.7.5,
            pydantic==1.9.1,
            sentry-sdk==1.6.0,
            sqlmodel==0.0.6,
          ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--exclude, tests, --recursive, .]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.18.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: ["--fix --ext .js,.jsx,.ts,.tsx"]
