version: "3.9"

services:
  e2e:
    build:
      context: .
      dockerfile: config/cypress.Dockerfile
    volumes:
      - ./e2e/cypress:/cypress
      - ./e2e/cypress.json:/cypress.json
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
