version: "3.9"

services:
  postgres:
    restart: always
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}

  backend:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: config/frontend.Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    environment:
      - BROWSER=none
      - CI=true
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: config/nginx.Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx/nginx.conf:/var/nginx.conf
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    command: "celery -A app.celery worker -l INFO"

  celery-beat:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    command: "celery -A app.celery beat -l INFO"

  flower:
    image: mher/flower
    ports:
      - 8888:8888
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
