version: "3.9"

services:
  postgres:
    restart: always
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_DB: ${DATABASE_NAME}

  backend:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: config/frontend.Dockerfile
    depends_on:
      - backend
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: config/nginx.Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "3000:80"
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: "celery -A app.celery worker -l INFO"

  celery-beat:
    build:
      context: .
      dockerfile: config/backend.Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: "celery -A app.celery beat -l INFO"

  redis:
    image: redis:6.2.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
