services:
  e2e:
    build:
      context: .
      dockerfile: config/cypress.Dockerfile
    volumes:
      - ./e2e/cypress:/cypress
      - ./e2e/cypress.json:/cypress.json
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx
