variable "application_environment" {}
variable "prefix" {}
variable "key_pair_name" {}
variable "domain_name" {}
variable "db_password" {}
variable "secret_key" {}
variable "app_name" {}
variable "smtp_host" {}
variable "smtp_port" {}
variable "smtp_user" {}
variable "smtp_password" {}
variable "email_sender" {}
variable "sentry_dsn" {}
