services:
  frontend:
    build:
      context: ../../
      dockerfile: config/frontend/Dockerfile
    depends_on:
      - backend
    volumes:
      - $PWD/frontend/src:/frontend/src
      - $PWD/frontend/public:/frontend/public
    environment:
      - BROWSER=none
      - CI=true

  nginx:
    build:
      context: ../../
      dockerfile: config/nginx/Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "3000:80"
    volumes:
      - $PWD/config/nginx/nginx.conf:/var/nginx.conf
    env_file:
      - .env

  flower:
    image: mher/flower
    ports:
      - "8888:8888"
    env_file:
      - .env
