services:
  backend:
    environment:
      - DEV_MODE=off

  proxy:
    build:
      context: ../../
      dockerfile: config/proxy/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost"]
      interval: 5s
      timeout: 15s
      retries: 12
    depends_on:
      - backend
    volumes:
      - $PWD/config/proxy/ssl/fullchain.pem:/etc/letsencrypt/live/localhost/fullchain.pem
      - $PWD/config/proxy/ssl/privkey.pem:/etc/letsencrypt/live/localhost/privkey.pem

  celery:
    environment:
      - DEV_MODE=off

  celery-beat:
    environment:
      - DEV_MODE=off

  e2e:
    image: cypress/included:9.6.1
    volumes:
      - $PWD/e2e/cypress:/cypress
      - $PWD/e2e/cypress.json:/cypress.json
    depends_on:
      proxy:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://proxy
