services:
  backend:
    environment:
      - DEV_MODE=off

  proxy:
    build:
      context: ../../
      dockerfile: config/proxy/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost"]
      interval: 5s
      timeout: 15s
      retries: 12
    depends_on:
      - backend

  celery:
    environment:
      - DEV_MODE=off

  celery-beat:
    environment:
      - DEV_MODE=off

  e2e:
    build:
      context: ../../
      dockerfile: config/e2e/Dockerfile
    volumes:
      - $PWD/e2e/cypress:/e2e/cypress
      - $PWD/e2e/cypress.config.ts:/e2e/cypress.config.ts
    depends_on:
      proxy:
        condition: service_healthy
    env_file:
      - .env
