services:
  backend:
    environment:
      - DEV_MODE=off

  proxy:
    build:
      context: ../../
      dockerfile: config/nginx/Dockerfile.prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 5s
      timeout: 15s
      retries: 12
    depends_on:
      - backend

  celery:
    environment:
      - DEV_MODE=off

  celery-beat:
    environment:
      - DEV_MODE=off

  e2e:
    image: cypress/included:9.6.1
    volumes:
      - $PWD/e2e/cypress:/cypress
      - $PWD/e2e/cypress.json:/cypress.json
    depends_on:
      proxy:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://proxy
