name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to be deployed"
        required: true
        default: "testing"
        type: choice
        options:
          - testing
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.environment }}
      - name: Build
        run: make build-prod
      - name: Push
        run: make push
      - name: Deploy
        run: make deploy
