name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to be deployed
        required: true
        default: testing
        type: choice
        options:
          - testing
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build
        run: make build-prod
      - name: Push
        run: make push
      - name: Deploy
        run: make deploy
