name: Lint and Test
on:
  pull_request:
  push:
    branches: [main, testing, staging, production]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy .env file
        run: cp config/compose/.env.template config/compose/.env
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy .env file
        run: cp config/compose/.env.template config/compose/.env
      - name: Build
        run: make build-e2e
      - name: Test
        run: make test-e2e
