name: Lint and Test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint-and-test: # TODO: Split to two separate jobs running in parallel (The built container has to be shared across jobs)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy .env file
        run: cp .env.template .env
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy .env file
        run: cp .env.template .env
      - name: Build
        run: make build-e2e
      - name: Test
        run: make test-e2e
